# Generated by Django 3.1.7 on 2021-06-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlposting',
            name='name',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
